module.exports = [
  { _id: 'boating', attribute: 'agility' },
  { _id: 'climbing', attribute: 'strength' },
  { _id: 'driving', attribute: 'agility' },
  { _id: 'fighting', attribute: 'agility' },
  { _id: 'gambling', attribute: 'smarts' },
  { _id: 'healing', attribute: 'smarts' },
  { _id: 'intimidation', attribute: 'spirit' },
  { _id: 'investigation', attribute: 'smarts' },
  { _id: 'knowledge', attribute: 'smarts' },
  { _id: 'lockpicking', attribute: 'agility' },
  { _id: 'notice', attribute: 'smarts' },
  { _id: 'persuasion', attribute: 'spirit' },
  { _id: 'piloting', attribute: 'agility' },
  { _id: 'repair', attribute: 'smarts' },
  { _id: 'riding', attribute: 'agility' },
  { _id: 'shooting', attribute: 'agility' },
  { _id: 'stealth', attribute: 'agility' },
  { _id: 'streetwise', attribute: 'smarts' },
  { _id: 'survival', attribute: 'smarts' },
  { _id: 'swimming', attribute: 'agility' },
  { _id: 'taunt', attribute: 'smarts' },
  { _id: 'throwing', attribute: 'agility' },
  { _id: 'tracking', attribute: 'smarts' },
];
